"""Custom tools directory for dynamically generated bioinformatics tools.

This directory contains Python modules generated by the Tool Builder Agent.
Each module is a wrapper for a bioinformatics tool that has been:

1. Discovered through literature mining or user request
2. Researched for API/CLI documentation
3. Generated as a Python wrapper
4. Validated for basic functionality
5. Registered in the tool registry

Tools in this directory are automatically loaded and made available
to agents in the BioAgents framework.

To manually add a tool:
1. Create a Python file with your tool function
2. Use the Tool Builder Agent or register_custom_tool to add metadata
"""
